#!/usr/bin/env bash
# Generates the OS boot script and binds the extra IPs immediately.
set -euo pipefail

SCRIPT_PATH="/usr/local/bin/vps-stack-bind-ips.sh"

echo "=== Generating Boot Script ($SCRIPT_PATH) ==="
sudo tee "$SCRIPT_PATH" >/dev/null <<EOF
#!/usr/bin/env bash
# =====================================================================
# AUTO-GENERATED BY scripts/bind-extra-ips.sh
# 
# List:   ip addr show eth0
# Delete: sudo ip addr del <IP> dev eth0
# =====================================================================

EOF

if [ -f .env ]; then
    grep -v '^#' .env | grep -E '_(IPV4|IPV6)=' | grep -i -v '^VPS_' | while IFS='=' read -r key value; do
        # Strip quotes and carriage returns
        value=$(echo "$value" | tr -d '"'\''\r')
        
        if [ -z "$value" ]; then continue; fi

        if [[ "$key" == *"_IPV4" ]]; then
            sudo tee -a "$SCRIPT_PATH" >/dev/null <<< "ip addr add $value dev eth0 2>/dev/null || true"
        elif [[ "$key" == *"_IPV6" ]]; then
            sudo tee -a "$SCRIPT_PATH" >/dev/null <<< "ip -6 addr add ${value}/64 dev eth0 2>/dev/null || true"
        fi
    done
fi

sudo chmod +x "$SCRIPT_PATH"

echo "=== Executing Bindings ==="
sudo "$SCRIPT_PATH"
echo "Success! IPs bound."
